"use client";
import { Card } from "@/components/ui";

export function LineChart({ values, labels, title, subtitle, onPointClick }: { values:number[]; labels:string[]; title:string; subtitle?:string; onPointClick?:(index:number)=>void }) {
  const gradientId = `lineFill-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;
  const w=640,h=230,p=28,max=Math.max(...values,1),min=Math.min(...values,0); const points=values.map((v,i)=>{const x=p+(i*(w-p*2))/Math.max(values.length-1,1);const y=h-p-((v-min)/(max-min||1))*(h-p*2);return [x,y] as const}); const d=points.map((p,i)=>`${i?"L":"M"}${p[0]} ${p[1]}`).join(" ");
  return <Card className="p-5"><div><h3 className="font-semibold">{title}</h3><p className="text-xs text-slate-500">{subtitle}</p></div><div className="mt-4 overflow-x-auto"><svg viewBox={`0 0 ${w} ${h}`} className="min-w-[540px] w-full" role="img" aria-label={title}><defs><linearGradient id={gradientId} x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#818cf8" stopOpacity=".25"/><stop offset="1" stopColor="#818cf8" stopOpacity="0"/></linearGradient></defs><path d={`${d} L ${points.at(-1)?.[0] ?? p} ${h-p} L ${p} ${h-p} Z`} fill={`url(#${gradientId})`}/><path d={d} fill="none" stroke="#818cf8" strokeWidth="3" strokeLinecap="round"/>{points.map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="7" fill="transparent" onClick={()=>onPointClick?.(i)} className="cursor-pointer"/><circle cx={x} cy={y} r="3.5" fill="#a5b4fc"/><text x={x} y={h-8} textAnchor="middle" className="fill-slate-500 text-[10px]">{labels[i]}</text></g>)}</svg></div></Card>;
}

export function BarChart({ data, title, subtitle, onBarClick, money=false }: { data:{label:string;value:number}[]; title:string; subtitle?:string; onBarClick?:(label:string)=>void; money?:boolean }) {
  const max=Math.max(...data.map(x=>x.value),1);
  return <Card className="p-5"><h3 className="font-semibold">{title}</h3><p className="text-xs text-slate-500">{subtitle}</p><div className="mt-6 flex h-52 items-end gap-3">{data.map((d)=><button key={d.label} title={`${d.label}: ${money?`₹${d.value.toLocaleString()}`:d.value}`} onClick={()=>onBarClick?.(d.label)} className="group flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><div className="w-full max-w-10 rounded-t-lg bg-indigo-500/70 transition group-hover:bg-indigo-400" style={{height:`${Math.max(4,(d.value/max)*100)}%`}}/><span className="w-full truncate text-center text-[10px] text-slate-500">{d.label}</span></button>)}</div></Card>;
}

export function DonutChart({ segments, title, centerLabel }: { segments:{label:string;value:number;className:string}[]; title:string; centerLabel:string }) {
  const total=segments.reduce((s,x)=>s+x.value,0)||1; let start=0; const conic=segments.map(s=>{const from=start/total*360;start+=s.value;const to=start/total*360;const color=s.className.includes("emerald")?"#34d399":s.className.includes("amber")?"#fbbf24":"#f87171";return `${color} ${from}deg ${to}deg`}).join(",");
  return <Card className="p-5"><h3 className="font-semibold">{title}</h3><div className="mt-5 flex items-center gap-5"><div className="relative grid h-36 w-36 shrink-0 place-items-center rounded-full" style={{background:`conic-gradient(${conic})`}}><div className="grid h-24 w-24 place-items-center rounded-full bg-slate-950 text-center"><span className="text-lg font-bold">{centerLabel}</span></div></div><div className="space-y-3 text-xs">{segments.map(s=><div key={s.label} className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${s.className}`}/><span className="text-slate-400">{s.label}</span><span className="font-semibold">{s.value}%</span></div>)}</div></div></Card>;
}

export function Funnel({ items, title, onClick }: { items:{label:string;value:number}[]; title:string; onClick?:(label:string)=>void }) { const max=Math.max(...items.map(x=>x.value),1); return <Card className="p-5"><h3 className="font-semibold">{title}</h3><div className="mt-5 space-y-3">{items.map((x,i)=><button key={x.label} onClick={()=>onClick?.(x.label)} className="block w-full text-left"><div className="mb-1 flex justify-between text-xs"><span>{x.label}</span><span className="text-slate-500">{x.value}</span></div><div className="h-8 overflow-hidden rounded-xl bg-white/[.04]"><div className="grid h-full place-items-center rounded-xl bg-gradient-to-r from-indigo-500/80 to-violet-500/60 text-[11px] font-medium" style={{width:`${Math.max(18,(x.value/max)*100)}%`}}>{i===items.length-1?"Won":""}</div></div></button>)}</div></Card>; }
