"use client";
import { Button, Card, Input, Select } from "@/components/ui";
import type { CustomerFilters, CustomerStatus } from "@/types/customer";
const statuses: CustomerStatus[] = ["Active","Inactive","Prospect","Lead","Archive"];
export function FilterPanel({ value, onChange, onClear, onSave }: { value: CustomerFilters; onChange:(v:CustomerFilters)=>void; onClear:()=>void; onSave:()=>void }) {
  const toggle=(key:"statuses"|"companies", item:string)=>onChange({...value,[key]:value[key].includes(item as never)?value[key].filter(x=>x!==item):[...value[key],item]});
  const companies=["Acme Corp","Innovatech","Globex","Nexora Labs","Vertex Systems","Orbit Works"];
  return <Card className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Advanced Filter Builder</h3><p className="text-xs text-slate-500">Combine search, status, company, date, phone and email without losing context.</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={onClear}>Clear All</Button><Button size="sm" onClick={onSave}>Save Custom Filter</Button></div></div><div className="mt-4 grid gap-4 lg:grid-cols-4"><div><p className="mb-2 text-xs font-medium text-slate-400">Status</p><div className="space-y-2">{statuses.map(s=><label key={s} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.statuses.includes(s)} onChange={()=>toggle("statuses",s)}/>{s}</label>)}</div></div><div><p className="mb-2 text-xs font-medium text-slate-400">Company</p><div className="space-y-2">{companies.map(c=><label key={c} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.companies.includes(c)} onChange={()=>toggle("companies",c)}/>{c}</label>)}</div></div><div className="space-y-3"><label className="block text-xs text-slate-400">Last Contact From<Input type="date" value={value.from} onChange={e=>onChange({...value,from:e.target.value})}/></label><label className="block text-xs text-slate-400">Last Contact To<Input type="date" value={value.to} onChange={e=>onChange({...value,to:e.target.value})}/></label><label className="block text-xs text-slate-400">Minimum Deal Value<Input type="number" min="0" value={value.minDeal} onChange={e=>onChange({...value,minDeal:e.target.value})}/></label></div><div className="space-y-3"><label className="block text-xs text-slate-400">Phone partial match<Input value={value.phone} onChange={e=>onChange({...value,phone:e.target.value})} placeholder="+91 98"/></label><label className="block text-xs text-slate-400">Email partial match<Input value={value.email} onChange={e=>onChange({...value,email:e.target.value})} placeholder="@company"/></label><div className="rounded-xl bg-indigo-500/10 p-3 text-xs text-indigo-200">Tip: filters apply instantly and remain active with the global search.</div></div></div></Card>;
}
